### ISSUE TITLE
Module doesn't appear to have made any changes to search

### ISSUE THREAD

**Issue by bknazook** [Daniel-KM/Omeka-S-module-AdvancedSearchPlus#2]
I'm not sure what went wrong, but I installed the module on Omeka S and just... nothing. There are no options to configure the module that I can see to make the new search features appear. Is there something I'm overlooking in order to turn this 'on'?

**Comment by Daniel-KM** [comment]
Indeed, there are no options, only new fields added in the default advanced search form.
